### ISSUE TITLE
Expand static ship classes to further differentiate ships

### ISSUE THREAD

**Issue by Coopss** [Coopss/eve-killboard-analyzer#2]
e.g. split faction/non-faction ships

https://github.com/Coopss/eve-killboard-analyzer/blob/master/src/ship_classes.py

**Comment by rdansro** [comment]
Here is a db I put together with class, type, faction, tech level, name, ID, and general role for each ship. Could not push to branch access denied.
[ships.zip](https://github.com/Coopss/eve-killboard-analyzer/files/2024475/ships.zip)

**Comment by Coopss** [comment]
@rdansro integrated in c24c1d5f7d95df104aa4d35d0979e664610f9cf1
